### ISSUE TITLE
TypeError: pomodoro.pomodoro.MainWindow.insertTasks() argument after * must be an iterable, not NoneType

### ISSUE THREAD

**Issue by allanlaal** [burakmartin/pomodoro#2]
doesn't run a second time:
  
  Traceback (most recent call last):
    File "/abin/pomodoro", line 8, in <module>
      sys.exit(main())
    File "/home/allan/.local/lib/python3.10/site-packages/pomodoro/pomodoro.py", line 530, in main
      mainWindow = MainWindow()
    File "/home/allan/.local/lib/python3.10/site-packages/pomodoro/pomodoro.py", line 52, in __init__
      self.setupUi()
    File "/home/allan/.local/lib/python3.10/site-packages/pomodoro/pomodoro.py", line 116, in setupUi
      tasksWidget = self.setupTasksTab()
    File "/home/allan/.local/lib/python3.10/site-packages/pomodoro/pomodoro.py", line 266, in setupTasksTab
      self.insertTasks(*settings.value(tasksKey, []))
  TypeError: pomodoro.pomodoro.MainWindow.insertTasks() argument after * must be an iterable, not NoneTyp

**Comment by Nbdyleto** [comment]
change `self.insertTasks(*settings.value(tasksKey, []))` to `self.insertTasks()` 
work to me
